CREATE TYPE ACTION AS ENUM ('INCOME', 'WITHDRAW', 'BUY', 'SELL');
CREATE TYPE CURRENCY_TYPE AS ENUM ('EUR', 'USD', 'HUF');

CREATE TABLE CASH_INPUT(
    time TIMESTAMPTZ NOT NULL,
    action ACTION NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    currency CURRENCY_TYPE NOT NULL
);

CREATE TABLE BOND_INPUT(
    time TIMESTAMPTZ NOT NULL,
    action ACTION NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    interest NUMERIC(12,2) NOT NULL,
    expiration TIMESTAMPTZ NOT NULL
);

CREATE TABLE STOCK_INPUT(
    time TIMESTAMPTZ NOT NULL,
    action ACTION NOT NULL,
    ticker TEXT NOT NULL,
    quantity NUMERIC(12,4) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    currency CURRENCY_TYPE NOT NULL
)